### PR TITLE
housekeeping

### PR DESCRIPTION
**Pull request by JacksonDorschner**

### CODE REVIEW

**Comment by Zachdehooge** [comment]
Formatting looks nice! It is however printing the current date and time, is that what you meant it to do? 
image

**Comment by Arch881010** [comment]
Also you didn't re-add example.env. ^^"

**Comment by Zachdehooge** [comment]
It looks like example.env got deleted with this commit, but I could be reading that wrong. If I remember correctly Nadocast publishes data three times a day that pertains to all of the metrics we would want (Hail, wind, tor). I will need to dig back into that and see when, but we may be able to utilize that!

**Comment by Arch881010** [comment]
Back on July 8th, 2024, it posted 4x.
image

**Comment by Arch881010** [comment]
After pulling this pr, example.env has been removed.

**Review by Zachdehooge — APPROVED** [review]

**Comment by Zachdehooge** [comment]
Readded the example.env in a seperate PR

**Comment by JacksonDorschner** [comment]
> Formatting looks nice! It is however printing the current date and time, is that what you meant it to do? image

sorry about that, I realized my mistake after a was about to fall asleep, will fix.

> a more local UTC version to use when retrieving the data. 

sorry if this is stupid, but im unclear of what you mean when you say more local, like with a z offset so it is the local time?

> (And sending the image by using [discord.py (how to send a local image)](https://discordpy.readthedocs.io/en/latest/faq.html?highlight=local%20image#how-do-i-upload-an-image)?) Thoughts?

I can work on this this morning if that works.

I will also add the line i added to example.env, that was an oversight by me, sorry.

**Pull request merged**
